# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: DEV_TEST # Ensure this pool is correctly configured

stages:

# Stage 1: Initialize Terraform
- stage: TerraformInit
  displayName: 'Terraform Initialize'
  jobs: 
  - job: TerraformInit
    displayName: 'Initialize Terraform Environment'
    steps: 
    - checkout: self # Ensure repo is checked out
    - script: |
        echo "Current directory:"
        pwd
        echo "Listing all files:"
        ls -lR
        cd ./Terraform-deployment
        terraform init -upgrade
      displayName: 'Run terraform init'

# Stage 2: Terraform Plan
- stage: TerraformPlan
  displayName: 'Terraform Plan'
  dependsOn: TerraformInit
  jobs:
  - job: TerraformPlan 
    displayName: 'Run Terraform Plan'
    steps: 
    - checkout: self # Ensure repo is checked out
    - script: |
        echo "Current directory:"
        pwd
        echo "Listing all files:"
        ls -lR
        cd ./Terraform-deployment 
        terraform plan -out main.tfplan
      displayName: 'Run terraform plan'

    
